// Wire types, derived from the daemon rather than described alongside it.
//
// `wire.ts` is generated by `npm run wire:generate` from `openapi.json`, which
// is a snapshot of `routes::openapi_spec()` asserted by
// `vtc-service/tests/openapi_snapshot.rs`. This module is the seam between the
// generated file and the console: it gives each schema the short name the
// plugins already use, so call sites read as they always did and nothing
// depends on the generator's `components["schemas"][…]` spelling.
//
// **The point is that no shape is written twice.** Before this, every type here
// was declared by hand beside the fetch that used it, and drifted the moment the
// daemon moved — six endpoints at once by the time #1186 found them, including
// both ways of signing in. A hand-written interface cannot be caught being
// wrong, because it *is* what `tsc` checks the console against. Aliasing the
// generated schema makes the daemon the only definition, so the next response
// change fails to compile here instead of returning `undefined` to an operator.
//
// To add one: find the schema in `wire.ts` and alias it. If it is missing, the
// route has no `body =` on its success response — fix that in the handler's
// `#[utoipa::path]`, which `openapi_response_census.rs` requires anyway.
//
// Two types are deliberately *not* here. `BuildInfo` (`/admin/build-info`) and
// `HealthResponse` (`/health`) are served outside the `/v1` mount that the
// document describes, so they have no schema to alias and stay hand-written in
// `api.ts`. They are also the two the console reads least structurally — a
// version string and a status word.

import type { components } from "./wire";

/** Every schema the daemon publishes, by name. */
export type Schemas = components["schemas"];

// ── Auth, session, passkeys ─────────────────────────────────────────────
export type SessionView = Schemas["SessionView"];
export type WhoamiResponse = Schemas["WhoamiResponse"];
export type SessionSummary = Schemas["SessionSummary"];
export type PasskeyLoginStartResponse = Schemas["PasskeyLoginStartResponse"];
export type RegisteredCredential = Schemas["RegisteredCredential"];
export type PasskeyListResponse = Schemas["ListResponse"];
export type PasskeyRegisterStartResponse = Schemas["RegisterStartResponse"];
export type PasskeyRevokeStartResponse = Schemas["RevokeStartResponse"];

// ── ACL + admin invites ─────────────────────────────────────────────────
export type AclEntry = Schemas["AclEntryResponse"];
export type AclEntryEnvelope = Schemas["AclEntryEnvelope"];
export type AclListResponse = Schemas["AclListResponse"];
export type InviteSummary = Schemas["InviteSummary"];
export type InvitesListResponse = Schemas["ListInvitesResponse"];
export type CreateInviteResponse = Schemas["CreateInviteResponse"];

// ── Members ─────────────────────────────────────────────────────────────
export type MemberRow = Schemas["MemberResponse"];
export type MemberEnvelope = Schemas["MemberEnvelope"];
export type MembersPage = Schemas["Paginated_MemberResponse"];
export type RemovedMemberRow = Schemas["RemovedMember"];
export type RemovedMembersResponse = Schemas["RemovedMembersResponse"];
export type RequestVmcResponse = Schemas["RequestVmcResponse"];

// ── Join requests ───────────────────────────────────────────────────────
export type JoinRequestRow = Schemas["JoinRequest"];
export type JoinRequestEnvelope = Schemas["JoinRequestEnvelope"];
export type JoinRequestsPage = Schemas["Paginated_JoinRequest"];
export type DecideResponse = Schemas["DecideResponse"];

// ── Audit ───────────────────────────────────────────────────────────────
export type AuditEntry = Schemas["AuditEntry"];
export type AuditListResponse = Schemas["AuditListResponse"];

// ── Policies ────────────────────────────────────────────────────────────
export type PolicyRow = Schemas["PolicyModuleResponse"];
export type PoliciesPage = Schemas["PolicyListResponse"];
export type ActiveBindingsResponse = Schemas["ActiveBindingsResponse"];
export type PolicyUpsertResponse = Schemas["UploadResponse"];
export type PolicyTestResponse = Schemas["TestResponse"];

// ── Community profile + ceremonies ──────────────────────────────────────
export type Profile = Schemas["ProfileWithStatus"];
export type ProfileResponse = Schemas["CommunityProfileResponse"];
export type CeremonyListResponse = Schemas["CeremonyListResponse"];

// ── Invitations, recognition, relationships, diagnostics ────────────────
export type InvitationListItem = Schemas["InvitationListItem"];
export type InvitationListResponse = Schemas["InvitationListResponse"];
export type IssueInvitationResponse = Schemas["IssueInvitationResponse"];
export type RecognitionCheck = Schemas["RecognitionCheck"];
export type RelationshipsGraph = Schemas["RelationshipsGraph"];
export type GraphNode = Schemas["GraphNode"];
export type GraphEdge = Schemas["GraphEdge"];
export type GraphHalf = Schemas["GraphHalf"];
export type DiagnosticsResponse = Schemas["DiagnosticsResponse"];
export type TransportStatus = Schemas["TransportStatus"];
export type RegistryTransport = Schemas["RegistryTransport"];
