// Wire types, derived from the daemon rather than described alongside it.
//
// `wire.ts` is generated by `npm run wire:generate` from `openapi.json`, which
// is a snapshot of `routes::openapi_spec()` asserted by
// `vtc-service/tests/openapi_snapshot.rs`. This module is the seam between the
// generated file and the console: it gives each schema the short name the
// plugins already use, so call sites read as they always did and nothing
// depends on the generator's `components["schemas"][…]` spelling.
//
// **The point is that no shape is written twice.** Before this, every type here
// was declared by hand beside the fetch that used it, and drifted the moment the
// daemon moved — six endpoints at once by the time #1186 found them, including
// both ways of signing in. A hand-written interface cannot be caught being
// wrong, because it *is* what `tsc` checks the console against. Aliasing the
// generated schema makes the daemon the only definition, so the next response
// change fails to compile here instead of returning `undefined` to an operator.
//
// To add one: find the schema in `wire.ts` and alias it. If it is missing, the
// route has no `body =` on its success response — fix that in the handler's
// `#[utoipa::path]`, which `openapi_response_census.rs` requires anyway.
//
// Two types are deliberately *not* here. `BuildInfo` (`/admin/build-info`) and
// `HealthResponse` (`/health`) are served outside the `/v1` mount that the
// document describes, so they have no schema to alias and stay hand-written in
// `api.ts`. They are also the two the console reads least structurally — a
// version string and a status word.

import type { components } from "./wire";

/** Every schema the daemon publishes, by name. */
export type Schemas = components["schemas"];

// ── Auth, session, passkeys ─────────────────────────────────────────────
export type SessionView = Schemas["SessionView"];
export type WhoamiResponse = Schemas["WhoamiResponse"];
export type SessionSummary = Schemas["SessionSummary"];
export type PasskeyLoginStartResponse =
  Schemas["AdminPasskeyLoginStartResponse"];
export type RegisteredCredential = Schemas["RegisteredCredential"];
export type PasskeyListResponse = Schemas["PasskeyListResponse"];
// Schema names are unique across the document — `openapi_schema_names.rs`
// holds that (#1697). Before it, `PasskeyListResponse` and
// `ConsoleKeyListResponse` were both published as `ListResponse` and the
// passkey endpoint was documented with the console-key shape.
export type ConsoleKey = Schemas["ConsoleKey"];
export type ConsoleKeyListResponse = Schemas["ConsoleKeyListResponse"];
export type ConsoleKeyRevokeResponse = Schemas["ConsoleKeyRevokeResponse"];
export type PasskeyRegisterStartResponse = Schemas["RegisterStartResponse"];
export type PasskeyRevokeStartResponse = Schemas["RevokeStartResponse"];

// ── ACL + admin invites ─────────────────────────────────────────────────
export type AclEntry = Schemas["AclEntryResponse"];
export type AclEntryEnvelope = Schemas["AclEntryEnvelope"];
export type AclListResponse = Schemas["AclListResponse"];
export type InviteSummary = Schemas["InviteSummary"];
export type InvitesListResponse = Schemas["ListInvitesResponse"];
export type CreateInviteResponse = Schemas["CreateInviteResponse"];

// ── Members ─────────────────────────────────────────────────────────────
export type MemberRow = Schemas["MemberResponse"];
export type MemberEnvelope = Schemas["MemberEnvelope"];
export type MembersPage = Schemas["Paginated_MemberResponse"];
export type RemovedMemberRow = Schemas["RemovedMember"];
export type RemovedMembersResponse = Schemas["RemovedMembersResponse"];
/** `vtc/members/credentials/0.1#response` — the membership pair's bodies. */
export type MemberCredentials = Schemas["VtcMembersCredentialsV0_1Response"];
export type EndorsementRow = Schemas["EndorsementRow"];
export type EndorsementsPage = Schemas["Paginated_EndorsementRow"];
export type VetterGrantResponse = Schemas["VtcVettingVettersGrantV0_1Response"];

// ── Vetter registry (admin) ─────────────────────────────────────────────
//
// The Trust Task bodies below are the published specifications' own: their
// schemas are named `<slug><version><definition>` and rendered from the schema
// each generated type embeds, not described by hand.
export type VetterGrantList = Schemas["VetterGrantListResponse"];
export type VetterGrantRow = Schemas["VetterGrantRow"];
export type VetterProfileSummary = Schemas["VetterProfileSummary"];
export type VetterGrantOrigin = Schemas["GrantOrigin"];
export type VetterResendResponse = Schemas["VtcVettingVettersResendV0_1Response"];
export type AutoGrantStatus = Schemas["AutoGrantStatus"];
export type AutoGrantConfig = Schemas["AutoGrantConfig"];
export type AutoGrantSweep = Schemas["AutoGrantSweep"];
export type VettingRevocationList = Schemas["VettingRevocationListResponse"];
export type VettingRevocationRow = Schemas["VettingRevocationRow"];
export type RevocationReviewState = Schemas["RevocationReviewState"];
/** The vetting vocabulary, as `vtc/join-requests/manifest/0.2` defines it. */
export type VettingMethod = Schemas["VtcJoinRequestsManifestV0_2VettingMethod"];
export type VettingRelationship = Schemas["VtcJoinRequestsManifestV0_2VettingRelationship"];
export type VetterListBody = Schemas["VtcVettingVettersListV0_1Payload"];
export type VetterListResponse = Schemas["VtcVettingVettersListV0_1Response"];
export type ListedVetter = Schemas["VtcVettingVettersListV0_1ListedVetter"];
export type VetterEvent = Schemas["VtcVettingVettersListV0_1VetterEvent"];
export type VetterLocation = Schemas["VtcVettingVettersListV0_1VetterLocation"];
/** `vtc/join-requests/manifest/0.2`'s branding — also the body of `/v1/community/branding`. */
export type CommunityBranding = Schemas["VtcJoinRequestsManifestV0_2CommunityBranding"];
export type RequestVmcResponse = Schemas["RequestVmcResponse"];

// ── Join requests ───────────────────────────────────────────────────────
export type JoinRequestRow = Schemas["JoinRequest"];
export type JoinRequestEnvelope = Schemas["JoinRequestEnvelope"];
export type JoinRequestsPage = Schemas["Paginated_JoinRequest"];
export type JoinRequestVettingResponse = Schemas["JoinRequestVettingResponse"];
export type JoinRequestVetting = Schemas["JoinRequestVetting"];
export type JoinRequestVettingStatement = Schemas["JoinRequestVettingStatement"];
export type JoinManifest = Schemas["VtcJoinRequestsManifestV0_2Response"];
export type ManifestCriterion = Schemas["VtcJoinRequestsManifestV0_2Criterion"];
export type VettingRequirements = Schemas["VtcJoinRequestsManifestV0_2VettingRequirements"];
export type DecideResponse = Schemas["DecideResponse"];

// ── Admission criteria + endorsement types ──────────────────────────────
//
// What the manifest publishes, the community stores as an Accepts criterion:
// the manifest criterion is the applicant's view (with its `requirementsDigest`)
// and `AcceptsCriterion` is the editable record behind it.
export type AcceptsCriterion = Schemas["AcceptsCriterion"];
export type RegisterAcceptsBody = Schemas["RegisterAcceptsBody"];
export type EndorsementType = Schemas["EndorsementType"];
export type EndorsementTypesPage = Schemas["Paginated_EndorsementType"];
/** `{ endorsementType: … }`, what `endorsement-types/register/0.1` publishes. */
export type EndorsementTypeRegistered = Schemas["RegisterResponse"];
export type RegisterEndorsementTypeBody = Schemas["RegisterBody"];
/** `{ typeUri }`, what `endorsement-types/delete/0.1` publishes. */
export type EndorsementTypeDeleted = Schemas["VtcEndorsementTypesDeleteV0_1Response"];

// ── Runtime config ──────────────────────────────────────────────────────
//
// The four-layer overlay (`env > db > toml > default`). `source` is what
// tells the console whether a value it is about to offer to edit is one it
// can actually change — an env override wins over the db layer a PATCH
// writes, so a control rendered without checking would silently do nothing.
export type EffectiveConfig = Schemas["EffectiveConfig"];
export type EffectiveField = Schemas["EffectiveField"];
export type ConfigPatchResponse = Schemas["PatchResponse"];

// ── Audit ───────────────────────────────────────────────────────────────
export type AuditEntry = Schemas["AuditEntry"];
export type AuditListResponse = Schemas["AuditListResponse"];

// ── Policies ────────────────────────────────────────────────────────────
export type PolicyRow = Schemas["PolicyModuleResponse"];
export type PoliciesPage = Schemas["PolicyListResponse"];
export type ActiveBindingsResponse = Schemas["ActiveBindingsResponse"];
export type PolicyUpsertResponse = Schemas["UploadResponse"];
export type PolicyTestResponse = Schemas["TestResponse"];
/**
 * What a policy decides.
 *
 * Aliased rather than re-listed because the console's own copy had gone stale:
 * it named ten purposes while the daemon served eleven, so the `rooms` policy —
 * the one deciding whether this community lends its disk, and whose shipped
 * default **denies** private rooms — was unreachable from the console entirely.
 * Nothing failed; the tab was simply not there.
 */
export type PolicyPurpose = Schemas["PolicyPurpose"];

// ── Rooms ───────────────────────────────────────────────────────────────
export type HostedRoom = Schemas["HostedRoom"];

// ── Community profile + ceremonies ──────────────────────────────────────
export type Profile = Schemas["ProfileWithStatus"];
export type ProfileResponse = Schemas["CommunityProfileResponse"];
export type CeremonyListResponse = Schemas["CeremonyListResponse"];

// ── Invitations, recognition, relationships, diagnostics ────────────────
export type InvitationListItem = Schemas["InvitationListItem"];
export type InvitationListResponse = Schemas["InvitationListResponse"];
export type IssueInvitationResponse = Schemas["IssueInvitationResponse"];
export type RecognitionCheck = Schemas["RecognitionCheck"];
export type RelationshipsGraph = Schemas["RelationshipsGraph"];
export type GraphNode = Schemas["GraphNode"];
export type GraphEdge = Schemas["GraphEdge"];
export type GraphHalf = Schemas["GraphHalf"];
export type DiagnosticsResponse = Schemas["DiagnosticsResponse"];
export type TransportStatus = Schemas["TransportStatus"];
export type TransportFinding = Schemas["Finding"];
export type TransportFindingCode = Schemas["FindingCode"];
export type DiagnosticsExt = Schemas["DiagnosticsExt"];
export type RegistryTransport = Schemas["RegistryTransport"];
export type FailedSyncJob = Schemas["FailedSyncJob"];
export type DriftSnapshot = Schemas["DriftSnapshot"];
export type DriftEntry = Schemas["DriftEntry"];

// ── Trust-registry operator surface ─────────────────────────────────────
//
// The published Trust Task shapes, not this service's own: the schemas are
// rendered from `vtc/registry/{sync-jobs,records}/…` so the console and the
// specification cannot disagree about a field name.
export type SyncJobsListResponse = Schemas["VtcRegistrySyncJobsListV0_1Response"];
export type SyncJobRow = Schemas["VtcRegistrySyncJobsListV0_1Job"];
export type SyncJobState = Schemas["VtcRegistrySyncJobsListV0_1State"];
export type SyncJobKind = Schemas["VtcRegistrySyncJobsListV0_1Kind"];
export type SyncJobsRetryResponse = Schemas["VtcRegistrySyncJobsRetryV0_1Response"];
export type SyncJobsDiscardResponse = Schemas["VtcRegistrySyncJobsDiscardV0_1Response"];
export type RegistryRecordsResponse = Schemas["VtcRegistryRecordsListV0_1Response"];
export type RegistryRecordRow = Schemas["VtcRegistryRecordsListV0_1Record"];

// ── Git namespaces (the Repos plugin) ───────────────────────────────────
//
// The administrator's read surface over `git-ns/*`. Every write is a signed
// Trust Task and has no REST shape here — see `plugins/repos/actions.ts`.
export type GitNsNamespaceRow = Schemas["GitNsNamespaceRow"];
export type GitNsRoleMap = Schemas["GitNsRoleMap"];
export type GitNsNamespaceList = Schemas["GitNsNamespaceList"];
export type GitNsRepoRow = Schemas["GitNsRepoRow"];
export type GitNsRepoList = Schemas["GitNsRepoList"];
export type GitNsBootstrapStatus = Schemas["GitNsBootstrapStatus"];
export type GitNsRightRow = Schemas["GitNsRightRow"];
export type GitNsRightList = Schemas["GitNsRightList"];
export type GitNsDepartedGrants = Schemas["GitNsDepartedGrants"];
export type GitNsDepartedGranter = Schemas["GitNsDepartedGranter"];
export type GitNsDriftList = Schemas["GitNsDriftList"];
export type GitNsDriftRow = Schemas["GitNsDriftRow"];
export type GitNsDriftItem = Schemas["GitNsViewV0_1DriftItem"];
export type GitNsJobList = Schemas["GitNsJobList"];
export type GitNsJobRow = Schemas["GitNsJobRow"];
export type GitNsProjection = Schemas["GitNsProjection"];
export type GitNsPublishedRow = Schemas["GitNsPublishedRow"];
export type GitNsRight = Schemas["GitNsViewV0_1Right"];
export type GitNsForgeStatus = Schemas["GitNsForgeStatus"];
export type GitNsStepOutcome = Schemas["GitNsStepOutcome"];
export type GitNsAccountRow = Schemas["GitNsAccountRow"];
export type GitNsAccountList = Schemas["GitNsAccountList"];
export type GitNsActivity = Schemas["GitNsActivity"];
export type GitNsActivityItem = Schemas["GitNsActivityItem"];
export type GitNsBreakGlassMark = Schemas["GitNsBreakGlassMark"];
export type GitNsBreakGlassItem = Schemas["GitNsBreakGlassItem"];
export type GitNsBreakGlassList = Schemas["GitNsBreakGlassList"];
