//! The schema-conformance sweep (#857): every task this dispatcher binds to a
//! **published** canonical URI must carry that URI's wire shape.
//!
//! ## Why this exists
//!
//! Two parity checks already run — every SDK constant is dispatched
//! (routing), and every dispatched `spec/` URI exists in the registry
//! (coverage, `vtc-service/tests/trust_task_manifest.rs`). Nothing checked
//! **correctness**: that a task bound to a published URI actually speaks that
//! URI's schema. Folding a task onto a *published* URI silently turns
//! `validate_payload` on at the dispatch spine, and a non-canonical body then
//! fails on live traffic with no compile-time signal — which is exactly how
//! `acl/update` shipped broken (#856, via #842).
//!
//! ## How it works
//!
//! The URI census is **derived, not hand-maintained**: `dispatched_uris()`
//! (generated by `dispatch_table!` from the same declarations as the match
//! arms) filtered to what `trust_tasks_rs::schema_index::schema_for`
//! resolves. Every URI in that set MUST have an entry in [`table`] — a
//! [`Witness`] carrying a representative request and response, or an
//! annotated [`Conformance::KnownDrift`] debt entry. The witness's request
//! must parse as the generated `specs::…::Payload` and the response as
//! `specs::…::Response`; the generated types carry `deny_unknown_fields`
//! plus the spec's required set, so the round-trip *is* the conformance
//! check.
//!
//! **Non-vacuity is enforced mechanically.** The `acl/update` defect
//! survived three PRs because an assertion of the form "adding a forbidden
//! member makes this fail" passed while the body was *already* failing for
//! an unrelated reason. Here every witness is drifted (an unknown member is
//! injected) after the good case passes, and the drifted form MUST be
//! rejected — a schema that accepts anything cannot produce a green row.
//!
//! ## When this fails after a rebase
//!
//! Sibling consolidation streams are rebinding URIs. A newly bound published
//! URI fails the coverage assertion here **by design** — add a witness (or,
//! with a stated reason, a debt entry) for it. That is this check doing its
//! job, not an obstacle to route around.
//!
//! It has already happened once, and the shape is worth keeping: #864 folded
//! the `did-templates` family onto new URIs, the census dropped the old ones,
//! and the *stale-witness* direction of the coverage assertion fired. Both
//! directions matter — a witness for a URI nothing dispatches any more is as
//! much drift as a dispatched URI with no witness, and only the first tells
//! you a fold landed.

use serde::de::DeserializeOwned;
use serde_json::{Value, json};
use std::collections::BTreeSet;

use trust_tasks_rs::specs;
use vta_sdk::trust_tasks as uris;

use vta_sdk::acl::ContextDirection;
use vta_sdk::protocols::acl_management::change_role::ChangeRoleBody;
use vta_sdk::protocols::acl_management::create::{CreateAclBody, CreateAclResponseBody};
use vta_sdk::protocols::acl_management::delete::{DeleteAclBody, DeleteAclResultBody};
use vta_sdk::protocols::acl_management::entry::{AclEntry, Approve, StepUp};
use vta_sdk::protocols::acl_management::get::{GetAclBody, GetAclResultBody};
use vta_sdk::protocols::acl_management::list::{ListAclBody, ListAclResultBody};
use vta_sdk::protocols::acl_management::swap::{SwapKeyBody, SwapKeyResultBody};
use vta_sdk::protocols::acl_management::update::UpdateAclBody;
use vta_sdk::protocols::audit_management::list::{
    AuditEnvelope, ListAuditLogsBody, ListAuditLogsResultBody,
};
use vta_sdk::protocols::auth::{RevokeSessionRequest, RevokeSessionResponse};
use vta_sdk::protocols::credential_exchange::{
    self as credx, PendingApproveBody, PendingDenyBody, PendingDenyResponse, PendingListResponse,
    PendingPresentationSummary, PresentBody, RequestedCredentialSummary,
};
use vta_sdk::protocols::credentials_issuance::{
    IssueCredentialBody, IssueCredentialResponse, RevokeCredentialBody, RevokeCredentialResponse,
};
use vta_sdk::protocols::memory::{
    MemoryDeleteBody, MemoryDeleteResponse, MemoryItem, MemoryListBody, MemoryListResponse,
    MemoryPutBody, MemoryPutResponse,
};
use vta_sdk::protocols::vta_management::get_config::{
    ConfigField, GetConfigBody, GetConfigResultBody,
};
use vta_sdk::protocols::vta_management::update_config::{
    RejectedKey, UpdateConfigBody, UpdateConfigResultBody,
};

use super::dispatched_uris;

/// The sweep's scope: dispatched ∩ published. Derived, never hand-listed.
fn resolved_uris() -> BTreeSet<&'static str> {
    dispatched_uris()
        .into_iter()
        .filter(|u| trust_tasks_rs::schema_index::schema_for(u).is_some())
        .collect()
}

type ParseFn = fn(Value) -> Result<(), String>;

fn parses<T: DeserializeOwned>(v: Value) -> Result<(), String> {
    serde_json::from_value::<T>(v)
        .map(|_| ())
        .map_err(|e| e.to_string())
}

/// A representative request/response pair for one published, dispatched URI.
///
/// The request is, wherever a public producer/consumer type exists, the
/// serialization of that type — so the assertion is about **our wire form**,
/// not about a hand-typed fixture. Where the slice's wire type is
/// module-private (consent, task-consent, vault), the fixture replicates the
/// handler's emission and the comment names the type it mirrors.
struct Witness {
    request: Value,
    parse_request: ParseFn,
    response: Value,
    parse_response: ParseFn,
}

enum Conformance {
    Checked(Witness),
    /// Known non-conformance, kept visible and counted instead of silently
    /// tolerated. Every entry is a follow-up issue; the reason must name the
    /// drift precisely enough that the fix needs no re-diagnosis.
    #[allow(dead_code)] // empty today — the variant is the mechanism for future debt
    KnownDrift(&'static str),
}

macro_rules! checked {
    ($p:ty, $r:ty, $req:expr, $resp:expr) => {
        Conformance::Checked(Witness {
            request: $req,
            parse_request: parses::<$p>,
            response: $resp,
            parse_response: parses::<$r>,
        })
    };
}

// ─── Shared fixture builders ─────────────────────────────────────────────

const SUBJECT: &str = "did:key:z6MkSubject";
const TS: &str = "2026-07-29T00:00:00Z";

fn dt() -> chrono::DateTime<chrono::Utc> {
    chrono::DateTime::parse_from_rfc3339(TS)
        .expect("valid ts")
        .with_timezone(&chrono::Utc)
}

/// A fully-populated canonical `AclEntry` (the family's shared component).
fn acl_entry() -> AclEntry {
    AclEntry {
        subject: SUBJECT.into(),
        role: "reader".into(),
        scopes: vec!["ctx-a".into()],
        label: Some("build agent".into()),
        created_at: Some(dt()),
        created_by: Some("did:key:z6MkAdmin".into()),
        updated_at: Some(dt()),
        updated_by: Some("did:key:z6MkAdmin".into()),
        expires_at: Some(dt()),
        step_up: Some(StepUp {
            approver: Some("did:key:z6MkApprover".into()),
            require: Some("delegated".into()),
        }),
        approve: Some(Approve {
            all: false,
            scopes: vec!["ctx-a".into()],
        }),
    }
}

fn to_v<T: serde::Serialize>(t: T) -> Value {
    serde_json::to_value(t).expect("serialize fixture")
}

/// The `Session` object the auth slice emits (whoami / sessions/list /
/// step-up elevation) — mirrors the `json!` shapes in `auth.rs` / `step_up.rs`.
fn session_json() -> Value {
    json!({
        "id": "sess-1",
        "subject": SUBJECT,
        "issuedAt": TS,
        "expiresAt": TS,
        "amr": ["swk"],
        "acr": "aal2",
    })
}

/// A wire `DeviceBinding` as `operations::device::to_wire_binding` emits it.
fn device_binding_json() -> Value {
    json!({
        "deviceId": "dev-1",
        "consumerKind": { "kind": "companion", "formFactor": "browser" },
        "displayName": "Laptop",
        "registeredAt": TS,
        "consumerDid": SUBJECT,
        "platform": "macOS",
        "pushCapable": false,
    })
}

/// A canonical `ConsentSubject` — mirrors `consent.rs`'s `WireSubject`.
fn consent_subject_json() -> Value {
    json!({
        "platform": "slack",
        "conversationRef": "conv-9f3",
        "kind": "dm",
        "agent": "agent-1",
    })
}

/// A fully-populated wire `VaultEntry` (`vti_common::vault::VaultEntry`,
/// authored against the canonical `vault/_shared` component).
fn vault_entry() -> vti_common::vault::VaultEntry {
    use vti_common::vault::{SecretKind, SiteTarget, VaultEntry};
    VaultEntry {
        id: "01HVAULTENTRY".into(),
        context_id: "ctx-a".into(),
        targets: vec![SiteTarget::WebOrigin {
            origin: "https://example.com".into(),
        }],
        label: "example.com login".into(),
        secret_kind: SecretKind::Password,
        tags: vec!["work".into()],
        notes: Some("shared team login".into()),
        favicon: None,
        selectors: vec![],
        custom_field_names: vec![],
        attachments: vec![],
        expires_at: Some(TS.into()),
        breached_at: None,
        password_changed_at: Some(TS.into()),
        created_at: TS.into(),
        created_by: Some(SUBJECT.into()),
        updated_at: TS.into(),
        updated_by: Some(SUBJECT.into()),
        last_used_at: Some(TS.into()),
        version: 3,
        principal_did: None,
        // Active entries omit the whole lifecycle block on the wire
        // (`skip_serializing_if`), which is what keeps them canonical — the
        // published `VaultEntry` component predates the archival lifecycle.
        status: vti_common::vault::VaultStatus::Active,
        archived_at: None,
        deleted_at: None,
        grace_until: None,
    }
}

// ─── The witness table ───────────────────────────────────────────────────

/// One entry per URI in [`resolved_uris`] — the coverage assertion below
/// holds the two in lockstep, in both directions.
///
/// `#[allow(deprecated)]` for the same reason the dispatch table carries it:
/// the 0.1 constants are deprecated in favour of their 0.2 siblings but are
/// still dispatched during the migration window, so they are still in the
/// census this table must cover.
#[allow(deprecated)]
fn table() -> Vec<(&'static str, Conformance)> {
    let mut t: Vec<(&'static str, Conformance)> = vec![
        // ─── auth ────────────────────────────────────────────────
        (
            uris::TASK_AUTH_REVOKE_SESSION_0_1,
            checked!(
                specs::auth::revoke_session::v0_1::Payload,
                specs::auth::revoke_session::v0_1::Response,
                to_v(RevokeSessionRequest {
                    session_id: "sess-1".into(),
                }),
                to_v(RevokeSessionResponse { revoked_count: 1 })
            ),
        ),
        (
            uris::TASK_AUTH_WHOAMI_0_1,
            checked!(
                specs::auth::whoami::v0_1::Payload,
                specs::auth::whoami::v0_1::Response,
                json!({}), // whoami has no request members; the handler ignores the payload
                json!({ "session": session_json(), "roles": ["admin"], "scopes": ["ctx:root"] })
            ),
        ),
        (
            uris::TASK_AUTH_SESSIONS_LIST_0_1,
            checked!(
                specs::auth::sessions::list::v0_1::Payload,
                specs::auth::sessions::list::v0_1::Response,
                json!({}),
                json!({ "sessions": [session_json()] })
            ),
        ),
        (
            uris::TASK_AUTH_STEP_UP_APPROVE_RESPONSE_0_1,
            checked!(
                specs::auth::step_up::approve_response::v0_1::Payload,
                specs::auth::step_up::approve_response::v0_1::Response,
                // 0.1 wire: kebab-case evidence discriminator.
                json!({
                    "subject": SUBJECT,
                    "sessionId": "sess-1",
                    "challenge": "chal-0123456789abcdef",
                    "decision": "approved",
                    "grantedAcr": "aal2",
                    "evidence": { "kind": "did-signed" },
                }),
                json!({ "status": "elevated", "session": session_json() })
            ),
        ),
        (
            uris::TASK_AUTH_STEP_UP_APPROVE_RESPONSE_0_2,
            checked!(
                specs::auth::step_up::approve_response::v0_2::Payload,
                specs::auth::step_up::approve_response::v0_2::Response,
                // 0.2 wire: camelCase evidence discriminator — the member the
                // handler kebabizes on a copy (`wire_v0_2::kebabize_paths`).
                json!({
                    "subject": SUBJECT,
                    "sessionId": "sess-1",
                    "challenge": "chal-0123456789abcdef",
                    "decision": "approved",
                    "grantedAcr": "aal2",
                    "evidence": { "kind": "didSigned" },
                }),
                json!({ "status": "elevated", "session": session_json() })
            ),
        ),
        (
            uris::TASK_AUTH_STEP_UP_POLICY_0_2,
            checked!(
                specs::auth::step_up::policy::v0_2::Payload,
                specs::auth::step_up::policy::v0_2::Response,
                // Handler parses the generated Payload directly; this mirrors
                // `operations::step_up_policy::effective_response`'s shape.
                json!({
                    "enabled": true,
                    "floors": [{
                        "operation": "acl/grant",
                        "mode": "delegated",
                        "allowAal1IfNonEscalating": true,
                    }],
                }),
                json!({
                    "enabled": true,
                    "floors": [{ "operation": "acl/grant", "mode": "delegated" }],
                })
            ),
        ),
        // ─── consent (types are consent.rs-private; fixtures mirror them) ──
        (
            uris::TASK_CONSENT_REQUEST_1_0,
            checked!(
                specs::consent::request::v1_0::Payload,
                specs::consent::request::v1_0::Response,
                json!({
                    "subject": consent_subject_json(),
                    "scope": "converse",
                    "challenge": "chal-0123456789abcdef",
                    "contextHint": "ctx-a",
                }),
                json!({ "status": "accepted", "requestId": "chal-1" })
            ),
        ),
        (
            uris::TASK_CONSENT_DECISION_1_0,
            checked!(
                specs::consent::decision::v1_0::Payload,
                specs::consent::decision::v1_0::Response,
                json!({
                    "subject": consent_subject_json(),
                    "effect": "allow",
                    "scope": "converse",
                    "challenge": "chal-0123456789abcdef",
                    "expiresAt": TS,
                }),
                json!({ "status": "recorded", "grantId": "urn:uuid:6d9c" })
            ),
        ),
        (
            uris::TASK_CONSENT_REVOKE_1_0,
            checked!(
                specs::consent::revoke::v1_0::Payload,
                specs::consent::revoke::v1_0::Response,
                json!({ "subject": consent_subject_json(), "reason": "operator revoked" }),
                json!({ "status": "revoked" })
            ),
        ),
        (
            uris::TASK_CONSENT_LIST_1_0,
            checked!(
                specs::consent::list::v1_0::Payload,
                specs::consent::list::v1_0::Response,
                json!({ "platform": "slack", "agent": "agent-1" }),
                json!({ "grants": [{
                    "subject": consent_subject_json(),
                    "effect": "allow",
                    "scope": "converse",
                    "grantedBy": "did:key:z6MkKeeper",
                    "grantedAt": TS,
                    "expiresAt": TS,
                    "evidence": "did-signed",
                }] })
            ),
        ),
        (
            uris::TASK_CONSENT_APPROVER_SET_1_0,
            checked!(
                specs::consent::approver_set::v1_0::Payload,
                specs::consent::approver_set::v1_0::Response,
                json!({
                    "platform": "slack",
                    "context": "ctx-a",
                    "approver": "did:key:z6MkKeeper",
                    "route": "wake",
                    "routeHint": "gateway-1",
                }),
                json!({ "status": "set" })
            ),
        ),
        (
            uris::TASK_CONSENT_APPROVER_LIST_1_0,
            checked!(
                specs::consent::approver_list::v1_0::Payload,
                specs::consent::approver_list::v1_0::Response,
                json!({ "platform": "slack" }),
                json!({ "approvers": [{
                    "platform": "slack",
                    "context": "ctx-a",
                    "approver": "did:key:z6MkKeeper",
                    "route": "wake",
                }] })
            ),
        ),
        // ─── task-consent (types are task_consent.rs-private) ─────
        (
            uris::TASK_TASK_CONSENT_DECISION_0_1,
            checked!(
                specs::task_consent::decision::v0_1::Payload,
                specs::task_consent::decision::v0_1::Response,
                json!({
                    "challenge": "chal-0123456789abcdef",
                    "payloadDigest": "b64u-digest",
                    "decision": "approve",
                    "reason": "looks right",
                }),
                json!({
                    "status": "pending",
                    "payloadDigest": "b64u-digest",
                    "approvals": 1,
                    "needed": 2,
                })
            ),
        ),
        // ─── acl ─────────────────────────────────────────────────
        (
            uris::TASK_ACL_LIST_0_1,
            checked!(
                specs::acl::list::v0_1::Payload,
                specs::acl::list::v0_1::Response,
                to_v(ListAclBody {
                    role: Some("reader".into()),
                    scope: Some("ctx-a".into()),
                    direction: Some(ContextDirection::Subtree),
                    subject_prefix: Some("did:key:z6Mk".into()),
                    page_size: Some(50),
                    cursor: Some("cur-1".into()),
                }),
                to_v(ListAclResultBody {
                    entries: vec![acl_entry()],
                    truncated: false,
                    cursor: None,
                    redacted_fields: Vec::new(),
                })
            ),
        ),
        (
            uris::TASK_ACL_GRANT_0_1,
            checked!(
                specs::acl::grant::v0_1::Payload,
                specs::acl::grant::v0_1::Response,
                to_v(CreateAclBody {
                    entry: acl_entry(),
                    reason: Some("onboarding".into()),
                }),
                to_v(CreateAclResponseBody { entry: acl_entry() })
            ),
        ),
        (
            uris::TASK_ACL_SHOW_0_1,
            checked!(
                specs::acl::show::v0_1::Payload,
                specs::acl::show::v0_1::Response,
                to_v(GetAclBody {
                    subject: SUBJECT.into(),
                }),
                to_v(GetAclResultBody {
                    entry: acl_entry(),
                    redacted_fields: Vec::new(),
                })
            ),
        ),
        (
            uris::TASK_ACL_UPDATE_0_1,
            checked!(
                specs::acl::update::v0_1::Payload,
                specs::acl::update::v0_1::Response,
                to_v(UpdateAclBody {
                    did: SUBJECT.into(),
                    label: Some("renamed".into()),
                    allowed_contexts: Some(vec!["ctx-a".into(), "ctx-b".into()]),
                    expires_at: Some(dt()),
                    reason: Some("access review".into()),
                    step_up: Some(StepUp {
                        approver: Some("did:key:z6MkApprover".into()),
                        require: Some("delegated".into()),
                    }),
                    approve: Some(Approve {
                        all: false,
                        scopes: vec!["ctx-a".into()],
                    }),
                }),
                to_v(CreateAclResponseBody { entry: acl_entry() })
            ),
        ),
        (
            uris::TASK_ACL_CHANGE_ROLE_0_1,
            checked!(
                specs::acl::change_role::v0_1::Payload,
                specs::acl::change_role::v0_1::Response,
                to_v(ChangeRoleBody {
                    subject: SUBJECT.into(),
                    from_role: "reader".into(),
                    to_role: "application".into(),
                    reason: Some("promoted".into()),
                }),
                to_v(CreateAclResponseBody { entry: acl_entry() })
            ),
        ),
        (
            uris::TASK_ACL_REVOKE_0_1,
            checked!(
                specs::acl::revoke::v0_1::Payload,
                specs::acl::revoke::v0_1::Response,
                to_v(DeleteAclBody {
                    subject: SUBJECT.into(),
                    scopes: Some(vec!["ctx-a".into()]),
                    reason: Some("offboarding".into()),
                }),
                to_v(DeleteAclResultBody { entry: acl_entry() })
            ),
        ),
        (
            uris::TASK_ACL_SWAP_KEY_0_1,
            checked!(
                specs::acl::swap_key::v0_1::Payload,
                specs::acl::swap_key::v0_1::Response,
                to_v(SwapKeyBody {
                    current_subject: SUBJECT.into(),
                    new_subject: "did:key:z6MkNewSubject".into(),
                    link_proof: "eyJhbGciOiJFZERTQSJ9.e30.c2ln".into(),
                    reason: Some("wallet rotation".into()),
                }),
                to_v(SwapKeyResultBody {
                    entry: acl_entry(),
                    previous_subject: SUBJECT.into(),
                })
            ),
        ),
        // ─── device (handlers parse the generated Payloads directly;
        //     responses mirror operations::device's json! emissions) ──
        (
            uris::TASK_DEVICE_REGISTER_0_1,
            checked!(
                specs::device::register::v0_1::Payload,
                specs::device::register::v0_1::Response,
                json!({
                    "consumerKind": { "kind": "companion", "formFactor": "browser" },
                    "displayName": "Laptop",
                    "platform": "macOS",
                    "keyCustody": { "tier": "hardware" },
                    "attestation": { "kind": "none" },
                }),
                json!({ "binding": device_binding_json() })
            ),
        ),
        (
            uris::TASK_DEVICE_HEARTBEAT_0_1,
            checked!(
                specs::device::heartbeat::v0_1::Payload,
                specs::device::heartbeat::v0_1::Response,
                json!({ "platform": "macOS", "vaultSeq": 42 }),
                json!({ "serverTime": TS, "queuedOperations": [], "syncHint": "up-to-date" })
            ),
        ),
        (
            uris::TASK_DEVICE_LIST_0_1,
            checked!(
                specs::device::list::v0_1::Payload,
                specs::device::list::v0_1::Response,
                json!({ "consumerKindFilter": "companion", "includeDisabled": true }),
                json!({ "devices": [device_binding_json()], "truncated": false })
            ),
        ),
        (
            uris::TASK_DEVICE_DISABLE_0_1,
            checked!(
                specs::device::disable::v0_1::Payload,
                specs::device::disable::v0_1::Response,
                json!({ "deviceId": "dev-1", "reason": "lost" }),
                json!({ "deviceId": "dev-1", "disabledAt": TS })
            ),
        ),
        (
            uris::TASK_DEVICE_WIPE_0_1,
            checked!(
                specs::device::wipe::v0_1::Payload,
                specs::device::wipe::v0_1::Response,
                json!({ "deviceId": "dev-1", "scope": "full", "reason": "stolen", "issuedAt": TS }),
                json!({ "deviceId": "dev-1", "scope": "full", "completedAt": TS })
            ),
        ),
        (
            uris::TASK_DEVICE_SET_WAKE_0_1,
            checked!(
                specs::device::set_wake::v0_1::Payload,
                specs::device::set_wake::v0_1::Response,
                json!({
                    "wakeHandle": { "gateway": "did:web:gateway.example", "handle": "h-1" },
                    "pushPlatform": "apns",
                    "suggestedTriggers": ["did:web:mediator.example"],
                }),
                json!({
                    "pushCapable": true,
                    "triggerPolicy": { "allowedTriggers": ["did:web:mediator.example"] },
                })
            ),
        ),
        // ─── messaging ───────────────────────────────────────────
        (
            uris::TASK_MESSAGING_PING_0_1,
            checked!(
                specs::messaging::ping::v0_1::Payload,
                specs::messaging::ping::v0_1::Response,
                json!({ "nonce": "n-1" }),
                json!({ "serverTime": TS, "status": "ok", "protocols": ["didcomm/v2"], "nonce": "n-1" })
            ),
        ),
        // ─── audit ───────────────────────────────────────────────
        (
            uris::TASK_AUDIT_LIST_0_1,
            checked!(
                specs::audit::list::v0_1::Payload,
                specs::audit::list::v0_1::Response,
                to_v(ListAuditLogsBody {
                    from: Some(dt()),
                    to: Some(dt()),
                    action: Some("acl.update".into()),
                    actor: Some(SUBJECT.into()),
                    outcome: Some("success".into()),
                    context_id: Some("ctx-a".into()),
                    page_size: Some(100),
                    cursor: Some("cur-1".into()),
                }),
                to_v(ListAuditLogsResultBody {
                    entries: vec![AuditEnvelope {
                        event_id: "evt-1".into(),
                        recorded_at: TS.into(),
                        action: "acl.update".into(),
                        outcome: Some("success".into()),
                        actor: Some(SUBJECT.into()),
                        target: Some("did:key:z6MkTarget".into()),
                        context_id: Some("ctx-a".into()),
                        detail: serde_json::Map::new(),
                    }],
                    truncated: true,
                    cursor: Some("cur-2".into()),
                })
            ),
        ),
        // ─── credential-exchange: deferred presentations ─────────
        (
            credx::PENDING_LIST,
            checked!(
                specs::credential_exchange::pending::list::v0_1::Payload,
                specs::credential_exchange::pending::list::v0_1::Response,
                json!({}),
                to_v(PendingListResponse {
                    pending: vec![PendingPresentationSummary {
                        id: "thr-1".into(),
                        verifier_did: "did:web:verifier.example".into(),
                        requested: vec![RequestedCredentialSummary {
                            credential_query_id: "q-1".into(),
                            credential_id: "cred-1".into(),
                            claims: vec!["givenName".into()],
                        }],
                        purpose: "age verification".into(),
                        created_at: dt(),
                        expires_at: dt(),
                    }],
                })
            ),
        ),
        (
            credx::PENDING_APPROVE,
            checked!(
                specs::credential_exchange::pending::approve::v0_1::Payload,
                specs::credential_exchange::pending::approve::v0_1::Response,
                to_v(PendingApproveBody { id: "thr-1".into() }),
                to_v(PresentBody {
                    vp_token: json!({ "vp": {} }),
                })
            ),
        ),
        (
            credx::PENDING_DENY,
            checked!(
                specs::credential_exchange::pending::deny::v0_1::Payload,
                specs::credential_exchange::pending::deny::v0_1::Response,
                to_v(PendingDenyBody { id: "thr-1".into() }),
                to_v(PendingDenyResponse {
                    id: "thr-1".into(),
                    status: "denied".into(),
                })
            ),
        ),
        // ─── vault (types are vault.rs-private; fixtures mirror them,
        //     entries via the shared vti_common::vault::VaultEntry) ──
        (
            uris::TASK_VAULT_LIST_0_1,
            checked!(
                specs::vault::list::v0_1::Payload,
                specs::vault::list::v0_1::Response,
                json!({
                    "contextId": "ctx-a",
                    "targetOriginPrefix": "https://example.com",
                    "secretKind": "password",
                    "tag": "work",
                    "status": "active",
                    "pageSize": 20,
                }),
                json!({ "entries": [to_v(vault_entry())], "truncated": false })
            ),
        ),
        (
            uris::TASK_VAULT_GET_0_1,
            checked!(
                specs::vault::get::v0_1::Payload,
                specs::vault::get::v0_1::Response,
                json!({ "id": "01HVAULTENTRY" }),
                json!({ "entry": to_v(vault_entry()) })
            ),
        ),
        (
            uris::TASK_VAULT_UPSERT_0_1,
            checked!(
                specs::vault::upsert::v0_1::Payload,
                specs::vault::upsert::v0_1::Response,
                json!({
                    "contextId": "ctx-a",
                    "targets": [{ "kind": "web-origin", "origin": "https://example.com" }],
                    "label": "example.com login",
                    "secretKind": "password",
                    "tags": ["work"],
                    "sealedSecret": { "envelope": "didcomm-authcrypt", "jwe": "eyJwcm90ZWN0ZWQiOiJ..." },
                    "expectedVersion": 3,
                }),
                json!({ "entry": to_v(vault_entry()), "created": false })
            ),
        ),
        (
            uris::TASK_VAULT_DELETE_0_1,
            checked!(
                specs::vault::delete::v0_1::Payload,
                specs::vault::delete::v0_1::Response,
                json!({ "id": "01HVAULTENTRY", "expectedVersion": 3, "reason": "rotated away" }),
                json!({ "id": "01HVAULTENTRY", "deletedAt": TS, "graceUntil": TS })
            ),
        ),
        (
            uris::TASK_VAULT_RELEASE_0_1,
            checked!(
                specs::vault::release::v0_1::Payload,
                specs::vault::release::v0_1::Response,
                json!({
                    "entryId": "01HVAULTENTRY",
                    "target": { "kind": "web-origin", "origin": "https://example.com" },
                    "consumerContext": { "deviceId": "dev-1", "networkClass": "home" },
                    "ttlSecondsHint": 60,
                }),
                json!({
                    "sealedSecret": { "envelope": "didcomm-authcrypt", "jwe": "eyJwcm90ZWN0ZWQiOiJ..." },
                    "secretKind": "password",
                    "ttlSeconds": 60,
                })
            ),
        ),
        (
            uris::TASK_VAULT_PROXY_LOGIN_0_1,
            checked!(
                specs::vault::proxy_login::v0_1::Payload,
                specs::vault::proxy_login::v0_1::Response,
                json!({
                    "entryId": "01HVAULTENTRY",
                    "target": { "kind": "web-origin", "origin": "https://example.com" },
                    "nonce": "n-1",
                    "ttlSecondsHint": 60,
                }),
                // Mirrors `VaultProxyLoginResponseBody`: the session hints ride
                // in the vendor-namespaced `ext` (the canonical response object
                // is closed; #857).
                json!({
                    "sealedSessionBlob": { "envelope": "didcomm-authcrypt", "jwe": "eyJwcm90ZWN0ZWQiOiJ..." },
                    "ext": { "org.openvtc.vault-session": { "sessionId": "vs-1", "expiresAt": TS } },
                })
            ),
        ),
        (
            uris::TASK_VAULT_SIGN_TRUST_TASK_0_1,
            checked!(
                specs::vault::sign_trust_task::v0_1::Payload,
                specs::vault::sign_trust_task::v0_1::Response,
                json!({
                    "entryId": "01HVAULTENTRY",
                    "unsignedEnvelope": {
                        "id": "urn:uuid:7c11",
                        "type": "https://trusttasks.org/spec/messaging/ping/0.1",
                        "issuer": SUBJECT,
                        "recipient": "did:web:vta.example",
                        "issuedAt": TS,
                        "payload": { "nonce": "n-1" },
                    },
                }),
                json!({ "signedEnvelope": {
                    "id": "urn:uuid:7c11",
                    "type": "https://trusttasks.org/spec/messaging/ping/0.1",
                    "issuer": SUBJECT,
                    "recipient": "did:web:vta.example",
                    "issuedAt": TS,
                    "payload": { "nonce": "n-1" },
                    "proof": { "type": "DataIntegrityProof" },
                } })
            ),
        ),
        // ─── vta/credentials ─────────────────────────────────────
        (
            uris::TASK_VTA_CREDENTIALS_ISSUE_0_1,
            checked!(
                specs::vta::credentials::issue::v0_1::Payload,
                specs::vta::credentials::issue::v0_1::Response,
                to_v(IssueCredentialBody {
                    holder: SUBJECT.into(),
                    claims: json!({ "role": "agent" }),
                    credential_type: Some("AgentAuthorization".into()),
                    validity_seconds: 3600,
                    purpose: Some("agent onboarding".into()),
                    // Deliberately absent: `authorizationContext` is a member the
                    // published schema does not define, so a producer cannot
                    // send it through the validated transport at all.
                    authorization_context: None,
                }),
                to_v(IssueCredentialResponse {
                    credential_id: "cred-1".into(),
                    credential: json!({ "@context": [], "type": ["VerifiableCredential"] }),
                    expires_at: TS.into(),
                })
            ),
        ),
        (
            uris::TASK_VTA_CREDENTIALS_REVOKE_0_1,
            checked!(
                specs::vta::credentials::revoke::v0_1::Payload,
                specs::vta::credentials::revoke::v0_1::Response,
                to_v(RevokeCredentialBody {
                    credential_id: "cred-1".into(),
                    reason: Some("holder offboarded".into()),
                }),
                to_v(RevokeCredentialResponse {
                    credential_id: "cred-1".into(),
                    revoked_at: TS.into(),
                })
            ),
        ),
        // ─── vta/memory ──────────────────────────────────────────
        (
            uris::TASK_VTA_MEMORY_PUT_0_1,
            checked!(
                specs::vta::memory::put::v0_1::Payload,
                specs::vta::memory::put::v0_1::Response,
                to_v(MemoryPutBody {
                    context_id: "ctx-a".into(),
                    key: "greeting".into(),
                    value: "hello".into(),
                }),
                to_v(MemoryPutResponse {
                    key: "greeting".into(),
                })
            ),
        ),
        (
            uris::TASK_VTA_MEMORY_LIST_0_1,
            checked!(
                specs::vta::memory::list::v0_1::Payload,
                specs::vta::memory::list::v0_1::Response,
                to_v(MemoryListBody {
                    context_id: "ctx-a".into(),
                }),
                to_v(MemoryListResponse {
                    items: vec![MemoryItem {
                        key: "greeting".into(),
                        value: "hello".into(),
                    }],
                })
            ),
        ),
        (
            uris::TASK_VTA_MEMORY_DELETE_0_1,
            checked!(
                specs::vta::memory::delete::v0_1::Payload,
                specs::vta::memory::delete::v0_1::Response,
                to_v(MemoryDeleteBody {
                    context_id: "ctx-a".into(),
                    key: "greeting".into(),
                }),
                to_v(MemoryDeleteResponse {
                    key: "greeting".into(),
                })
            ),
        ),
        // ─── config ──────────────────────────────────────────────
        (
            uris::TASK_CONFIG_SHOW_0_1,
            checked!(
                specs::config::show::v0_1::Payload,
                specs::config::show::v0_1::Response,
                to_v(GetConfigBody {
                    keys: Some(vec!["public_url".into()]),
                }),
                to_v(GetConfigResultBody {
                    fields: vec![ConfigField {
                        key: "public_url".into(),
                        value: json!("https://vta.example"),
                        source: "db".into(),
                        requires_restart: false,
                    }],
                })
            ),
        ),
        (
            uris::TASK_CONFIG_PATCH_0_1,
            checked!(
                specs::config::patch::v0_1::Payload,
                specs::config::patch::v0_1::Response,
                to_v(UpdateConfigBody {
                    overrides: [("public_url".to_string(), json!("https://vta.example"))]
                        .into_iter()
                        .collect(),
                }),
                to_v(UpdateConfigResultBody {
                    applied: vec!["public_url".into()],
                    pending_restart: vec![],
                    rejected: vec![RejectedKey {
                        key: "vta_did".into(),
                        reason: "immutable".into(),
                    }],
                })
            ),
        ),
        // ─── vta/did-templates ───────────────────────────────────
        //
        // No witnesses, and that is correct right now. #864 folded the twelve
        // `vta/{contexts/,}did-templates/*/1.0` URIs onto the merged six-task
        // `vta/did-templates/*/2.0` family, and the 2.0 specs are published
        // upstream but not yet in the pinned `trust-tasks-rs` (the publish-lag
        // `vtc-service/tests/trust_task_manifest.rs` also records). So
        // `schema_for` resolves none of them and the derived census excludes
        // them. The next `trust-tasks-rs` bump puts all six back in scope and
        // the coverage assertion will ask for their witnesses — which is the
        // sweep working, not breaking.
    ];

    // ─── passkey-vms (feature-gated like their dispatch arms) ─────
    #[cfg(all(feature = "webvh", feature = "didcomm"))]
    {
        use vta_sdk::protocols::did_management::passkey_vms as pk;
        fn vm() -> pk::PasskeyVerificationMethod {
            pk::PasskeyVerificationMethod {
                id: "did:webvh:scid:vta.example#passkey-1".into(),
                vm_type: "Multikey".into(),
                controller: "did:webvh:scid:vta.example".into(),
                public_key_multibase: "z6MkPasskey".into(),
                webauthn_credential_id: "b64u-cred-id".into(),
                webauthn_transports: vec!["internal".into()],
                label: Some("YubiKey".into()),
            }
        }
        t.extend([
            (
                uris::TASK_PASSKEY_VMS_ENROLL_CHALLENGE_0_1,
                checked!(
                    specs::vta::passkey_vms::enroll_challenge::v0_1::Payload,
                    specs::vta::passkey_vms::enroll_challenge::v0_1::Response,
                    to_v(pk::EnrollPasskeyChallengeBody {
                        did: "did:webvh:scid:vta.example".into(),
                        label: Some("YubiKey".into()),
                    }),
                    to_v(pk::EnrollPasskeyChallengeResponse {
                        ceremony_id: "cer-1".into(),
                        challenge: "b64u-challenge".into(),
                        rp_id: "vta.example".into(),
                        rp_name: "VTA".into(),
                        user_handle: "b64u-handle".into(),
                        user_name: "operator".into(),
                        user_display_name: "Operator".into(),
                        timeout_ms: Some(60_000),
                    })
                ),
            ),
            (
                uris::TASK_PASSKEY_VMS_ENROLL_SUBMIT_0_1,
                checked!(
                    specs::vta::passkey_vms::enroll_submit::v0_1::Payload,
                    specs::vta::passkey_vms::enroll_submit::v0_1::Response,
                    to_v(pk::EnrollPasskeySubmitBody {
                        did: "did:webvh:scid:vta.example".into(),
                        ceremony_id: "cer-1".into(),
                        credential_id: "b64u-cred-id".into(),
                        public_key_multibase: "z6MkPasskey".into(),
                        cose_algorithm: -8,
                        attestation_object: "b64u-atto".into(),
                        client_data_json: "b64u-cdj".into(),
                        authenticator_data: "b64u-authdata".into(),
                        transports: vec!["internal".into()],
                        label: Some("YubiKey".into()),
                    }),
                    to_v(pk::EnrollPasskeySubmitResponse {
                        verification_method: vm(),
                        webvh_version: "2-zVer".into(),
                    })
                ),
            ),
            (
                uris::TASK_PASSKEY_VMS_LIST_0_1,
                checked!(
                    specs::vta::passkey_vms::list::v0_1::Payload,
                    specs::vta::passkey_vms::list::v0_1::Response,
                    to_v(pk::ListPasskeyVmsBody {
                        did: "did:webvh:scid:vta.example".into(),
                    }),
                    to_v(pk::ListPasskeyVmsResponse {
                        verification_methods: vec![vm()],
                    })
                ),
            ),
            (
                uris::TASK_PASSKEY_VMS_REVOKE_0_1,
                checked!(
                    specs::vta::passkey_vms::revoke::v0_1::Payload,
                    specs::vta::passkey_vms::revoke::v0_1::Response,
                    to_v(pk::RevokePasskeyVmBody {
                        did: "did:webvh:scid:vta.example".into(),
                        fragment: "passkey-1".into(),
                    }),
                    to_v(pk::RevokePasskeyVmResponse::default())
                ),
            ),
        ]);
    }

    // ─── provision/integration (webvh-gated like its dispatch arm) ─
    #[cfg(feature = "webvh")]
    {
        use vta_sdk::provision_integration::http as prov;
        // The request is consumed, not produced, by this service, and the
        // VP-framed `request` member is signed material — the fixture is the
        // canonical document shape (0.2 camelCase, `templateBootstrap` ask
        // tag) that `ProvisionIntegrationRequest` dual-accepts.
        let request = json!({
            "request": {
                "@context": ["https://www.w3.org/ns/credentials/v2",
                             "https://openvtc.org/contexts/bootstrap-v1"],
                "type": ["VerifiablePresentation", "BootstrapRequest"],
                "id": "urn:uuid:9be7",
                "holder": "did:key:z6MkAgentSetup",
                "nonce": "AAAAAAAAAAAAAAAAAAAAAA",
                "validUntil": TS,
                "ask": { "type": "templateBootstrap", "template": { "name": "didcomm-mediator" } },
                "proof": {
                    "type": "DataIntegrityProof",
                    "cryptosuite": "eddsa-jcs-2022",
                    "created": TS,
                    "verificationMethod": "did:key:z6MkAgentSetup#z6MkAgentSetup",
                    "proofPurpose": "authentication",
                    "proofValue": "z5TvSig",
                },
            },
            "context": "agents",
            "assertion": "didSigned",
            "vcValiditySeconds": 3600,
            "createContext": true,
        });
        let response = to_v(prov::ProvisionIntegrationResponse {
            bundle: "-----BEGIN VTA SEALED BUNDLE-----".into(),
            digest: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa".into(),
            summary: prov::ProvisionSummary {
                client_did: "did:key:z6MkAgentSetup".into(),
                admin_did: "did:key:z6MkAdmin".into(),
                admin_rolled_over: true,
                integration_did: Some("did:webvh:scid:agents.example".into()),
                template_name: Some("didcomm-mediator".into()),
                template_kind: Some("mediator".into()),
                admin_template_name: Some("vta-admin".into()),
                bundle_id_hex: "0123456789abcdef0123456789abcdef".into(),
                secret_count: 2,
                output_count: 1,
                webvh_server_id: Some("srv-1".into()),
                context_created: true,
            },
        });
        // Prove the canonical request also parses into our consumer type —
        // dual-accept means the fixture must satisfy both sides.
        serde_json::from_value::<prov::ProvisionIntegrationRequest>(request.clone())
            .expect("canonical provision request parses into ProvisionIntegrationRequest");
        t.push((
            uris::TASK_PROVISION_INTEGRATION_0_2,
            checked!(
                specs::provision::integration::v0_2::Payload,
                specs::provision::integration::v0_2::Response,
                request,
                response
            ),
        ));
    }

    // ─── vta/webvh/dids/update (webvh-gated like its dispatch arm) ─
    #[cfg(feature = "webvh")]
    {
        use vta_sdk::protocols::did_management::update::UpdateDidWebvhResultBody;
        t.push((
            uris::TASK_WEBVH_DIDS_UPDATE_1_0,
            checked!(
                specs::vta::webvh::dids::update::v1_0::Payload,
                specs::vta::webvh::dids::update::v1_0::Response,
                // Mirrors `webvh.rs`'s `UpdateDidWithDid` (did + flattened
                // camelCase `UpdateDidWebvhBody`).
                json!({
                    "did": "did:webvh:scid:vta.example",
                    "label": "rotate after audit",
                    "preRotationCount": 2,
                    "ttl": 3600,
                    "watchers": ["https://watcher.example"],
                    "expectedVersionId": "1-zVer",
                }),
                to_v(UpdateDidWebvhResultBody {
                    did: "did:webvh:scid:vta.example".into(),
                    new_version_id: "2-zVer".into(),
                    new_scid: "scid".into(),
                    new_log_entry: "{}".into(),
                    update_keys_count: 1,
                    pre_rotation_key_count: 2,
                    serverless: false,
                })
            ),
        ));
    }

    t
}

// ─── The sweep ───────────────────────────────────────────────────────────

/// Coverage: the witness table and the derived census agree exactly, in both
/// directions. A sibling stream rebinding a URI onto a published spec lands
/// here first — that is the point.
#[test]
fn every_published_dispatched_uri_has_a_witness() {
    let expected = resolved_uris();
    let mut covered = BTreeSet::new();
    for (uri, _) in table() {
        assert!(
            covered.insert(uri),
            "duplicate witness entry for {uri} — one entry per URI"
        );
    }

    let missing: Vec<_> = expected.difference(&covered).collect();
    assert!(
        missing.is_empty(),
        "these dispatched URIs are published in the registry but have no \
         conformance witness:\n  {}\n\nAdd a `checked!` entry (request + \
         response built from the slice's wire types), or — only for a real, \
         understood non-conformance — a `KnownDrift` entry with a reason. If \
         this fired after a rebase, a sibling consolidation stream rebound a \
         task onto a published URI; the sweep is asking for its witness.",
        missing
            .iter()
            .map(|s| s.to_string())
            .collect::<Vec<_>>()
            .join("\n  ")
    );

    let stale: Vec<_> = covered.difference(&expected).collect();
    assert!(
        stale.is_empty(),
        "these witnesses cover URIs that are no longer both dispatched and \
         published:\n  {}\n\nRemove them (or fix the constant they name).",
        stale
            .iter()
            .map(|s| s.to_string())
            .collect::<Vec<_>>()
            .join("\n  ")
    );
}

/// Correctness: every witness's request parses as the generated `Payload`
/// and its response as the generated `Response` — and the check has teeth:
/// a drifted (unknown-member) form of each MUST be rejected, so a witness
/// cannot pass vacuously against a schema that accepts anything.
#[test]
fn every_witnessed_task_round_trips_through_its_generated_types() {
    let mut drift: Vec<String> = Vec::new();

    for (uri, conformance) in table() {
        let w = match conformance {
            Conformance::Checked(w) => w,
            Conformance::KnownDrift(reason) => {
                assert!(
                    !reason.trim().is_empty(),
                    "{uri}: KnownDrift entries must state the drift"
                );
                drift.push(format!("{uri}: {reason}"));
                continue;
            }
        };

        (w.parse_request)(w.request.clone())
            .unwrap_or_else(|e| panic!("{uri}: request is not canonical: {e}\n{:#}", w.request));
        (w.parse_response)(w.response.clone())
            .unwrap_or_else(|e| panic!("{uri}: response is not canonical: {e}\n{:#}", w.response));

        // Teeth: an unknown member must be rejected on both sides. The
        // generated types carry `deny_unknown_fields` wherever the spec is
        // `additionalProperties: false` — which is every published task
        // today. A URI for which this stops holding needs a KnownDrift-style
        // review, not a silent pass.
        for (side, value, parse) in [
            ("request", &w.request, w.parse_request),
            ("response", &w.response, w.parse_response),
        ] {
            let mut drifted = value.clone();
            drifted
                .as_object_mut()
                .unwrap_or_else(|| panic!("{uri}: {side} witness must be a JSON object"))
                .insert("__conformance_sweep_drift".into(), json!(true));
            assert!(
                parse(drifted).is_err(),
                "{uri}: the generated {side} type accepted an unknown member — \
                 this witness can pass vacuously and proves nothing"
            );
        }
    }

    // Debt is visible in the test output every run, not buried in a table.
    for line in &drift {
        eprintln!("KNOWN DRIFT (follow-up issue required): {line}");
    }
}
