//! The declared-error-code census (#1600): every extended error code a bound,
//! published `spec/vtc/*` task **declares** must be witnessed by a test that
//! observes this service **emitting** it.
//!
//! ## Why this exists
//!
//! The schema-conformance sweep next door (`conformance.rs`) witnesses the
//! success path only. A specification can declare extended codes under SPEC
//! §8.5, the service can emit none of them, and every gate stays green. That
//! shipped: `vtc/join-requests/withdraw/0.1` (#1591) declares `notFound` and
//! `alreadyDecided`, and the handler answered both through the generic
//! `app_error_to_reject` as a bare `taskFailed`. The same shape recurred on
//! `supplement:*` (#1593). Each was caught by a test somebody happened to
//! write; nothing required it.
//!
//! ## How it works
//!
//! The census is **derived, not hand-maintained**. Its scope is the same
//! bound ∩ published URI set the conformance sweep uses
//! ([`super::conformance::resolved_uris`]), and for each URI the declared codes
//! come from `trust_tasks_rs::schema_index::error_codes_for` — generated by
//! `trust-tasks-codegen` from the specification's `errorCodes` front matter.
//! Nothing here spells a code as a string.
//!
//! Every declared code in scope must be in exactly one of:
//!
//! - [`witnesses`] — naming the integration test that drives the service into
//!   the code and asserts it. The census checks that the named test exists,
//!   that it asserts on an error code — `tt_error_code(` for a Trust Task
//!   error document, `rest_error_code(` for a REST-only route's `{"error",
//!   "code"}` body — and that it names the
//!   constant the witness carries — so a witness cannot point at a test that
//!   does not look at the code.
//! - [`UNWITNESSED`] — the baseline of declared codes nothing yet shows the
//!   service emitting. **It only shrinks**: a code that gains a witness must
//!   leave it (listing it in both fails), and its length is asserted, so a
//!   newly bound task cannot add codes to it unnoticed.
//!
//! The reverse direction — codes this service emits that its specification
//! does *not* declare — is [`CONSUMER_MINTED`]: each entry must stay
//! undeclared, so the day a specification adopts one the entry fails and asks
//! for the generated constant instead.
//!
//! ## What a witness proves, and what it does not
//!
//! A witness names a test; this file does not run it. It runs in the same
//! `cargo test -p vtc-service` invocation, so a witness naming a failing test
//! is a red build either way. What the census adds is the *requirement* that
//! such a test exist for every declared code, which is the thing that was
//! missing.

use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use trust_tasks_rs::DeclaredErrorCode;
use trust_tasks_rs::schema_index::error_codes_for;

use super::conformance::resolved_uris;

/// One declared code, and the test that observes the service emitting it.
struct Witness {
    declared: DeclaredErrorCode,
    /// The identifier the test compares against (`tt_error_code(&body) ==
    /// <via>`). Its value is asserted equal to `declared.code`, so it cannot
    /// name a different code.
    via: &'static str,
    via_value: &'static str,
    /// `tests/<file>`.
    file: &'static str,
    test_fn: &'static str,
}

/// `witness!(generated constant, identifier the test uses, "file.rs", "test_fn")`.
macro_rules! witness {
    ($declared:expr, $via:path, $file:literal, $test_fn:literal) => {
        Witness {
            declared: $declared,
            via: {
                let s = stringify!($via);
                match s.rfind("::") {
                    Some(i) => s.split_at(i + 2).1,
                    None => s,
                }
            },
            via_value: $via,
            file: $file,
            test_fn: $test_fn,
        }
    };
}

fn witnesses() -> Vec<Witness> {
    use trust_tasks_rs::specs::vtc as s;
    use vta_sdk::protocols::join_requests as jr;
    use vta_sdk::protocols::vetting as vet;

    vec![
        witness!(
            s::join_requests::withdraw::v0_1::error_codes::NOT_FOUND,
            jr::JOIN_REQUEST_WITHDRAW_ERR_NOT_FOUND,
            "join_requests.rs",
            "the_withdraw_task_answers_with_the_codes_its_spec_declares"
        ),
        witness!(
            s::join_requests::withdraw::v0_1::error_codes::ALREADY_DECIDED,
            jr::JOIN_REQUEST_WITHDRAW_ERR_ALREADY_DECIDED,
            "join_requests.rs",
            "the_withdraw_task_answers_with_the_codes_its_spec_declares"
        ),
        witness!(
            s::join_requests::supplement::v0_1::error_codes::NOT_FOUND,
            jr::JOIN_REQUEST_SUPPLEMENT_ERR_NOT_FOUND,
            "join_requests.rs",
            "the_supplement_task_answers_with_the_codes_its_spec_declares"
        ),
        witness!(
            s::join_requests::supplement::v0_1::error_codes::NOT_AWAITING_EVIDENCE,
            jr::JOIN_REQUEST_SUPPLEMENT_ERR_NOT_AWAITING_EVIDENCE,
            "join_requests.rs",
            "the_supplement_task_answers_with_the_codes_its_spec_declares"
        ),
        witness!(
            s::join_requests::supplement::v0_1::error_codes::ALREADY_DECIDED,
            jr::JOIN_REQUEST_SUPPLEMENT_ERR_ALREADY_DECIDED,
            "join_requests.rs",
            "the_supplement_task_answers_with_the_codes_its_spec_declares"
        ),
        witness!(
            s::join_requests::submit::v0_2::error_codes::ATTRIBUTES_MISSING,
            jr::JOIN_REQUEST_SUBMIT_ERR_ATTRIBUTES_MISSING,
            "join_requests.rs",
            "requested_attributes_are_published_enforced_and_kept_with_the_request"
        ),
        witness!(
            s::join_requests::submit::v0_2::error_codes::ATTRIBUTES_UNREQUESTED,
            jr::JOIN_REQUEST_SUBMIT_ERR_ATTRIBUTES_UNREQUESTED,
            "join_requests.rs",
            "requested_attributes_are_published_enforced_and_kept_with_the_request"
        ),
        witness!(
            s::vetting::vetters::profile::v0_1::error_codes::NOT_ELIGIBLE,
            vet::VETTING_VETTER_PROFILE_ERR_NOT_ELIGIBLE,
            "join_requests.rs",
            "only_a_member_holding_a_live_grant_may_publish_a_profile"
        ),
        witness!(
            s::vetting::vetters::resend::v0_1::error_codes::NOT_GRANTED,
            vet::VETTING_VETTER_RESEND_ERR_NOT_GRANTED,
            "join_requests.rs",
            "a_vetter_asks_for_the_grant_credential_again"
        ),
        witness!(
            s::members::credentials::v0_1::error_codes::NOT_FOUND,
            crate::routes::members::credentials::MEMBER_CREDENTIALS_ERR_NOT_FOUND,
            "members_crud.rs",
            "member_credentials_for_an_unknown_member_is_the_declared_not_found"
        ),
    ]
}

/// Declared codes nothing yet shows the service emitting. **Only shrinks.**
///
/// Typed paths, not strings: a code the specification stops declaring is a
/// compile error here, not a stale row.
fn unwitnessed() -> Vec<DeclaredErrorCode> {
    use trust_tasks_rs::specs::vtc as s;
    vec![
        // BASELINE-BEGIN — generated from this test's own failure output.
        s::admin::bootstrap::v0_1::error_codes::ALREADY_BOOTSTRAPPED,
        s::admin::bootstrap::v0_1::error_codes::INVALID_TOKEN,
        s::admin::invites::create::v0_1::error_codes::TTL_TOO_LONG,
        s::admin::invites::revoke::v0_1::error_codes::ALREADY_CONSUMED,
        s::admin::invites::revoke::v0_1::error_codes::NOT_FOUND,
        s::auth::admin_session::v0_1::error_codes::INVALID_TOKEN,
        s::auth::recognise::challenge::v0_1::error_codes::RATE_LIMITED,
        s::auth::recognise::v0_2::error_codes::CREDENTIAL_INVALID,
        s::auth::recognise::v0_2::error_codes::ISSUER_NOT_RECOGNISED,
        s::auth::recognise::v0_2::error_codes::ROLE_NOT_MAPPED,
        s::backup::export::v0_1::error_codes::PASSWORD_TOO_SHORT,
        s::backup::import::v0_1::error_codes::DECRYPTION_FAILED,
        s::community::profile::update::v0_1::error_codes::VALIDATION_FAILED,
        s::config::import::v0_1::error_codes::COMMUNITY_DID_MISMATCH,
        s::config::import::v0_1::error_codes::UNSUPPORTED_SCHEMA_VERSION,
        s::directory::query::v0_1::error_codes::NOT_FOUND,
        s::endorsement_types::delete::v0_1::error_codes::IN_USE,
        s::endorsement_types::delete::v0_1::error_codes::NOT_FOUND,
        s::endorsement_types::register::v0_1::error_codes::EXISTS,
        s::endorsement_types::register::v0_1::error_codes::INVALID_URI,
        s::endorsement_types::register::v0_1::error_codes::RESERVED,
        s::endorsements::issue::v0_1::error_codes::CLAIM_SCHEMA_VIOLATION,
        s::endorsements::issue::v0_1::error_codes::CLAIM_TOO_LARGE,
        s::endorsements::issue::v0_1::error_codes::STATUS_LIST_EXHAUSTED,
        s::endorsements::issue::v0_1::error_codes::TYPE_NOT_REGISTERED,
        s::endorsements::list::v0_1::error_codes::INVALID_CURSOR,
        s::endorsements::revoke::v0_1::error_codes::ALREADY_REVOKED,
        s::endorsements::revoke::v0_1::error_codes::NOT_FOUND,
        s::endorsements::show::v0_1::error_codes::NOT_FOUND,
        s::install::claim::finish::v0_2::error_codes::BINDING_INVALID,
        s::install::claim::finish::v0_2::error_codes::INVALID_TOKEN,
        s::install::claim::finish::v0_2::error_codes::REGISTRATION_MISMATCH,
        s::install::claim::start::v0_2::error_codes::INVALID_TOKEN,
        s::invitations::issue::v0_1::error_codes::UNKNOWN_ROLE,
        s::invitations::revoke::v0_1::error_codes::NOT_FOUND,
        s::join_requests::decide::v0_1::error_codes::NOT_FOUND,
        s::join_requests::decide::v0_1::error_codes::NOT_PENDING,
        s::join_requests::show::v0_1::error_codes::NOT_FOUND,
        s::join_requests::status::v0_1::error_codes::NOT_FOUND,
        s::join_requests::submit::v0_2::error_codes::POLICY_UNSATISFIED,
        s::join_requests::submit::v0_2::error_codes::PRESENTATION_INVALID,
        s::members::admin_remove::v0_1::error_codes::NOT_FOUND,
        s::members::personhood::assert::v0_1::error_codes::CHALLENGE_EXPIRED,
        s::members::personhood::assert::v0_1::error_codes::NOT_FOUND,
        s::members::personhood::assert::v0_1::error_codes::PRESENTATION_INVALID,
        s::members::personhood::challenge::v0_1::error_codes::NOT_FOUND,
        s::members::personhood::revoke::v0_1::error_codes::NOT_FOUND,
        s::members::purge::v0_1::error_codes::LAST_ADMINISTRATOR,
        s::members::purge::v0_1::error_codes::NOT_FOUND,
        s::members::renew::v0_1::error_codes::NOT_MEMBER,
        s::members::rotate::v0_1::error_codes::ROTATION_EXPIRED,
        s::members::rotate::v0_1::error_codes::SIGNATURE_INVALID,
        s::members::rotate_challenge::v0_1::error_codes::NOT_MEMBER,
        s::members::self_remove::v0_1::error_codes::NOT_MEMBER,
        s::members::show::v0_1::error_codes::NOT_FOUND,
        s::members::solicit_vmc::v0_1::error_codes::NOT_FOUND,
        s::members::update::v0_1::error_codes::ADMIN_ROLE_FORBIDDEN,
        s::members::update::v0_1::error_codes::NOT_FOUND,
        s::members::vmc::v0_1::error_codes::INVALID_CREDENTIAL,
        s::members::vmc::v0_1::error_codes::NOT_A_MEMBER,
        s::members::vmc::v0_1::error_codes::REQUEST_APPLICANT_MISMATCH,
        s::members::vmc::v0_1::error_codes::REQUEST_NOT_APPROVED,
        s::members::vmc::v0_1::error_codes::REQUEST_NOT_FOUND,
        s::members::vmc::v0_1::error_codes::SUBJECT_MISMATCH,
        s::policies::test::v0_1::error_codes::EVALUATION_FAILED,
        s::policies::test::v0_1::error_codes::NOT_FOUND,
        s::relationships::list::v0_2::error_codes::NOT_FOUND,
        s::relationships::publish::v0_2::error_codes::SUBJECT_NOT_MEMBER,
        s::relationships::publish::v0_2::error_codes::VRC_INVALID,
        s::relationships::revoke::v0_1::error_codes::NOT_FOUND,
        s::vetting::revoke_statement::v0_1::error_codes::DIGEST_MISMATCH,
        s::vetting::revoke_statement::v0_1::error_codes::ISSUER_MISMATCH,
        s::vetting::revoke_statement::v0_1::error_codes::NOT_MEMBER,
        s::vetting::vetters::grant::v0_1::error_codes::NOT_MEMBER,
        s::website::files::delete::v0_1::error_codes::NOT_FOUND,
        s::website::generations::list::v0_1::error_codes::NOT_MANAGED,
        s::website::rollback::v0_1::error_codes::GENERATION_NOT_FOUND,
        s::website::rollback::v0_1::error_codes::NOT_MANAGED,
        // BASELINE-END
    ]
}

/// The length of [`unwitnessed`], asserted. Lower it as witnesses land; raising
/// it means a newly bound task declares codes nothing tests, which is the
/// thing this census exists to stop.
const UNWITNESSED: usize = 78;

/// Extended codes this service emits that its specification does **not**
/// declare — minted under the task's own namespace, as SPEC §8.5 permits.
/// `(request Type URI, code)`.
const CONSUMER_MINTED: &[(&str, &str)] = &[(
    vta_sdk::protocols::join_requests::JOIN_REQUEST_SUBMIT_TYPE,
    vta_sdk::protocols::join_requests::JOIN_REQUEST_SUBMIT_ERR_REQUEST_ALREADY_OPEN,
)];

/// Every declared code in scope, keyed by code, with the URI declaring it.
fn declared_in_scope() -> BTreeMap<&'static str, (String, DeclaredErrorCode)> {
    let mut out = BTreeMap::new();
    for uri in resolved_uris() {
        let codes = error_codes_for(&uri).unwrap_or_else(|| {
            panic!(
                "{uri} resolves in schema_for but not in error_codes_for — the two \
                 indexes are generated from one loop and must agree"
            )
        });
        for declared in codes {
            out.insert(declared.code, (uri.clone(), *declared));
        }
    }
    out
}

/// The body of `fn <name>` in `text`, from its signature to the next line that
/// is a bare `}` — the shape rustfmt gives a top-level test function.
fn fn_body<'a>(text: &'a str, name: &str) -> Option<&'a str> {
    let start = text.find(&format!("fn {name}("))?;
    let rest = &text[start..];
    let end = rest.find("\n}\n").map_or(rest.len(), |i| i + 3);
    Some(&rest[..end])
}

/// The ready-to-paste baseline row for a declared code.
fn baseline_row(uri: &str, declared: &DeclaredErrorCode) -> String {
    let tail = uri
        .strip_prefix("https://trusttasks.org/spec/vtc/")
        .unwrap_or(uri);
    let (slug, version) = tail.rsplit_once('/').unwrap_or((tail, ""));
    let module = slug.replace('-', "_").replace('/', "::");
    let version = format!("v{}", version.replace('.', "_"));
    let mut ident = String::new();
    for (i, c) in declared.local().chars().enumerate() {
        if c.is_ascii_uppercase() && i > 0 {
            ident.push('_');
        }
        ident.push(c.to_ascii_uppercase());
    }
    format!("s::{module}::{version}::error_codes::{ident},")
}

#[test]
fn every_declared_error_code_is_witnessed_or_baselined() {
    let declared = declared_in_scope();
    assert!(
        !declared.is_empty(),
        "no bound, published spec/vtc/ task declares an error code — the census \
         is broken, not the code"
    );

    let tests_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests");
    let mut witnessed: BTreeSet<&'static str> = BTreeSet::new();
    for w in witnesses() {
        let code = w.declared.code;
        assert_eq!(
            w.via_value, code,
            "witness for {code}: `{}` is {:?}, not the code it claims to witness",
            w.via, w.via_value
        );
        assert!(
            declared.contains_key(code),
            "witness for {code}: no bound, published task declares it any more — \
             remove the witness"
        );
        assert!(witnessed.insert(code), "duplicate witness for {code}");

        let path = tests_dir.join(w.file);
        let text = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("witness for {code}: read {}: {e}", path.display()));
        let body = fn_body(&text, w.test_fn).unwrap_or_else(|| {
            panic!(
                "witness for {code}: tests/{} has no `fn {}`",
                w.file, w.test_fn
            )
        });
        assert!(
            (body.contains("tt_error_code(") || body.contains("rest_error_code("))
                && body.contains(w.via),
            "witness for {code}: `{}` in tests/{} must assert on the emitted code \
             (`tt_error_code(` or `rest_error_code(`) and name `{}` — a witness that \
             does not look at the code proves nothing",
            w.test_fn,
            w.file,
            w.via
        );
    }

    let baseline: Vec<DeclaredErrorCode> = unwitnessed();
    let mut baselined: BTreeSet<&'static str> = BTreeSet::new();
    for b in &baseline {
        assert!(
            declared.contains_key(b.code),
            "baseline lists {}, which no bound, published task declares any more — \
             remove it and lower UNWITNESSED",
            b.code
        );
        assert!(
            !witnessed.contains(b.code),
            "{} is witnessed AND baselined — remove it from the baseline and lower \
             UNWITNESSED; that is the baseline shrinking, which is the point",
            b.code
        );
        assert!(baselined.insert(b.code), "{} baselined twice", b.code);
    }

    let missing: Vec<String> = declared
        .iter()
        .filter(|(code, _)| !witnessed.contains(*code) && !baselined.contains(*code))
        .map(|(code, (uri, d))| format!("{code}  ({uri})\n      {}", baseline_row(uri, d)))
        .collect();
    assert!(
        missing.is_empty(),
        "these declared error codes have no witness and are not baselined:\n  {}\n\n\
         Write a test that drives the service into each and asserts the code, then add \
         a `witness!` row. Baselining is for codes that predate this census, not for \
         new tasks.",
        missing.join("\n  ")
    );

    assert_eq!(
        baseline.len(),
        UNWITNESSED,
        "the unwitnessed baseline changed size. Down: lower UNWITNESSED. Up: a bound \
         task declares codes nothing shows this service emitting."
    );
    eprintln!(
        "error-code census: {} declared in scope, {} witnessed, {} baselined",
        declared.len(),
        witnessed.len(),
        baseline.len()
    );
}

/// A consumer-minted code must stay undeclared, and stay under its own task's
/// namespace (SPEC §8.5).
#[test]
fn consumer_minted_codes_are_not_declared_by_their_specification() {
    for (uri, code) in CONSUMER_MINTED {
        let declared = error_codes_for(uri)
            .unwrap_or_else(|| panic!("{uri}: this build knows no specification for it"));
        assert!(
            !declared.iter().any(|d| d.code == *code),
            "{code} is now declared by {uri} — replace the hand-written constant with \
             the generated `error_codes` one, drop it from CONSUMER_MINTED, and witness it"
        );
        let slug = uri
            .strip_prefix("https://trusttasks.org/spec/")
            .and_then(|t| t.rsplit_once('/'))
            .map(|(slug, _)| slug)
            .expect("a Type URI");
        assert!(
            code.strip_prefix(slug)
                .is_some_and(|rest| rest.starts_with(':')),
            "{code} is not namespaced under {slug} (SPEC §8.5)"
        );
    }
}
